# CodeRabbit Configuration for MJCHAUFFAGE
# This file configures CodeRabbit AI code review settings

# Global settings
review:
  # Enable comprehensive code reviews
  enabled: true
  
  # Review frequency
  schedule: "on_pr_open,on_commit"
  
  # Languages to review
  languages:
    - typescript
    - javascript
    - json
    - yaml
    - markdown
    - sql

# Chat settings for AI assistance
chat:
  enabled: true
  # Allow asking questions about code
  questions: true

# Suggestions settings
suggestions:
  # Enable code improvement suggestions
  enabled: true
  
  # Focus areas for this project
  focus:
    - security
    - performance
    - best_practices
    - accessibility
    - maintainability

# Ignore patterns
ignore:
  # Ignore generated files
  patterns:
    - "**/node_modules/**"
    - "**/dist/**"
    - "**/build/**"
    - "**/.next/**"
    - "**/coverage/**"
    - "**/*.min.js"
    - "**/*.min.css"
    - "**/package-lock.json"
    - "**/yarn.lock"

# Project-specific settings
project:
  # This is a Next.js + Node.js marketplace application
  type: "web_application"
  
  # Key technologies
  technologies:
    - "Next.js"
    - "React"
    - "TypeScript"
    - "Node.js"
    - "Express"
    - "Prisma"
    - "PostgreSQL"
    - "TailwindCSS"
  
  # Focus on these areas for reviews
  review_focus:
    - "API security and validation"
    - "Database queries optimization"
    - "Frontend performance"
    - "Multilingual support (FR/AR)"
    - "E-commerce functionality"
    - "Admin dashboard security"

# Security settings
security:
  # Enable security-focused reviews
  enabled: true
  
  # Check for common vulnerabilities
  vulnerabilities:
    - "sql_injection"
    - "xss"
    - "csrf"
    - "authentication_bypass"
    - "insecure_dependencies"
